Other Version of Workflows

diff --git a/.github/workflows/ci_suite.yml b/.github/workflows/ci_suite.yml
--- a/.github/workflows/ci_suite.yml
+++ b/.github/workflows/ci_suite.yml
@@ -6,194 +6,245 @@ on:
   pull_request:
     branches:
       - main
-  merge_group:
-    branches:
-      - main
+env:
+  toolchain: stable
+  target: i686-unknown-linux-gnu
 jobs:
   run_linters:
-    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
+    if: "!contains(github.event.head_commit.message, '[ci skip]')"
     name: Run Linters
     runs-on: ubuntu-22.04
-    concurrency:
-      group: run_linters-${{ github.head_ref || github.run_id }}
-      cancel-in-progress: true
     steps:
       - uses: actions/checkout@v4
-      - name: Restore SpacemanDMM cache
+      - name: Setup cache
         uses: actions/cache@v4
         with:
           path: ~/SpacemanDMM
-          key: ${{ runner.os }}-spacemandmm-${{ hashFiles('dependencies.sh') }}
-          restore-keys: |
-            ${{ runner.os }}-spacemandmm-
-      - name: Restore Yarn cache
-        uses: actions/cache@v4
-        with:
-          path: tgui/.yarn/cache
-          key: ${{ runner.os }}-yarn-${{ hashFiles('tgui/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-
-      - name: Restore Node cache
-        uses: actions/cache@v4
-        with:
-          path: ~/.nvm
-          key: ${{ runner.os }}-node-${{ hashFiles('dependencies.sh') }}
-          restore-keys: |
-            ${{ runner.os }}-node-
-      - name: Restore Bootstrap cache
-        uses: actions/cache@v4
-        with:
-          path: tools/bootstrap/.cache
-          key: ${{ runner.os }}-bootstrap-${{ hashFiles('tools/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-bootstrap-
-      - name: Restore Rust cache
-        uses: actions/cache@v4
-        with:
-          path: ~/.cargo
-          key: ${{ runner.os }}-rust-${{ hashFiles('tools/ci/ci_dependencies.sh')}}
-          restore-keys: |
-            ${{ runner.os }}-rust-
-      - name: Restore Cutter cache
-        uses: actions/cache@v4
-        with:
-          path: tools/icon_cutter/cache
-          key: ${{ runner.os }}-cutter-${{ hashFiles('dependencies.sh') }}
-      - name: Install OpenDream
-        uses: robinraju/release-downloader@v1.9
-        with:
-          repository: "OpenDreamProject/OpenDream"
-          tag: "latest"
-          fileName: "DMCompiler_linux-x64.tar.gz"
-          extract: true
+          key: ${{ runner.os }}-spacemandmm-${{ secrets.CACHE_PURGE_KEY }}
       - name: Install Tools
+        run: bash tools/ci/install_spaceman_dmm.sh
+
+      - uses: actions/setup-python@v6
+        with:
+          python-version: "3.13"
+          cache: "pip"
+
+      - uses: actions/setup-node@v6
+        with:
+          node-version: 20
+          cache: "yarn"
+          cache-dependency-path: ./tgui/yarn.lock
+
+      - run: pip install -r tools/requirements.txt
+      - name: Run Linters
         run: |
-          pip3 install setuptools
-          bash tools/ci/install_node.sh
-          bash tools/ci/install_spaceman_dmm.sh dreamchecker
-          bash tools/ci/install_ripgrep.sh
-          tools/bootstrap/python -c ''
-      - name: Give Linters A Go
-        id: linter-setup
-        run: ":"
-      - name: Run Grep Checks
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: bash tools/ci/check_grep.sh
-      - name: Ticked File Enforcement
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: |
-          tools/bootstrap/python tools/ticked_file_enforcement/ticked_file_enforcement.py < tools/ticked_file_enforcement/schemas/tgstation_dme.json
-      - name: Check Define Sanity
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: tools/bootstrap/python -m define_sanity.check
-      - name: Run DreamChecker
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        shell: bash
-        run: ~/dreamchecker 2>&1 | bash tools/ci/annotate_dm.sh
-      - name: Run OpenDream
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: ./DMCompiler_linux-x64/DMCompiler tgstation.dme --suppress-unimplemented --define=CIBUILDING | bash tools/ci/annotate_od.sh
-      - name: Run Map Checks
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: |
+          bash tools/ci/check_filedirs.sh hailmary.dme
+          bash tools/ci/check_changelogs.sh
+          find . -name "*.php" -print0 | xargs -0 -n1 php -l
+          find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/json_verifier.py
+          tgui/bin/tgui --lint
+          tgui/bin/tgui --test
+          bash tools/ci/check_grep.sh
+          tools/bootstrap/python -m dmi.test
           tools/bootstrap/python -m mapmerge2.dmm_test
-          tools/bootstrap/python -m tools.maplint.source
-      - name: Check Cutter
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: tools/bootstrap/python -m tools.icon_cutter.check
-      - name: Check File Directories
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: bash tools/ci/check_filedirs.sh tgstation.dme
-      - name: Check Changelogs
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: bash tools/ci/check_changelogs.sh
-      - name: Check Miscellaneous Files
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: bash tools/ci/check_misc.sh
-      - name: Run TGUI Checks
-        if: steps.linter-setup.conclusion == 'success' && !cancelled()
-        run: tools/build/build --ci lint tgui-test
+          ~/dreamchecker 2>&1 | bash tools/ci/annotate_dm.sh
 
   compile_all_maps:
-    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
+    if: "!contains(github.event.head_commit.message, '[ci skip]')"
     name: Compile Maps
-    needs: [collect_data]
     runs-on: ubuntu-22.04
-    concurrency:
-      group: compile_all_maps-${{ github.head_ref || github.run_id }}
-      cancel-in-progress: true
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup cache
+        uses: actions/cache@v4
+        with:
+          path: ~/BYOND
+          key: ${{ runner.os }}-byond-${{ secrets.CACHE_PURGE_KEY }}
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "^18"
+      - name: Compile All Maps
+        run: |
+          bash tools/ci/install_byond.sh
+          source $HOME/BYOND/byond/bin/byondsetup
+          python3 tools/ci/template_dm_generator.py
+          tools/build/build dm -DCIBUILDING -DCITESTING -DALL_MAPS
+
+  # uncomment when they fix auxmos build
+  # auxmos:
+  #   if: "!contains(github.event.head_commit.message, '[ci skip]')"
+  #   name: Build Auxmos
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: "Putnam3145/auxmos"
+  #         ref: "6be702ec36d8024bfb93b4277004a9a755f5e92e"
+  #         path: "auxmos"
+
+  #     - name: Cache cargo registry
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cargo/registry
+  #         key: auxmos-registry-${{ hashFiles('auxmos/Cargo.lock') }}
+
+  #     - name: Cache cargo index
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cargo/git
+  #         key: auxmos-index-${{ hashFiles('auxmos/Cargo.lock') }}
+
+  #     - name: Cache cargo build
+  #       id: auxmos-cache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: auxmos/target
+  #         key: auxmos-build-target-${{ hashFiles('auxmos/Cargo.lock') }}
+
+  #     - name: Install Ubuntu Deps
+  #       if: steps.auxmos-cache.outputs.cache-hit != 'true'
+  #       run: |
+  #         sudo dpkg --add-architecture i386
+  #         sudo apt-get update
+  #         sudo apt install build-essential g++-multilib libc6-i386 libstdc++6:i386
+
+  #     - uses: actions-rs/toolchain@v1
+  #       if: steps.auxmos-cache.outputs.cache-hit != 'true'
+  #       with:
+  #         profile: minimal
+  #         toolchain: ${{env.toolchain}}
+  #         target: ${{env.target}}
+  #         override: true
+
+  #     - name: Build
+  #       if: steps.auxmos-cache.outputs.cache-hit != 'true'
+  #       run: |
+  #         cargo build --manifest-path auxmos/Cargo.toml --target=${{env.target}} --release --verbose
+  #         ldd auxmos/target/${{env.target}}/release/libauxmos.so
+
+  #     - name: Upload libauxmos artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: libauxmos
+  #         path: auxmos/target/${{env.target}}/release/libauxmos.so
+
+  run_all_tests:
+    if: "!contains(github.event.head_commit.message, '[ci skip]')"
+    name: Integration Tests
+    runs-on: ubuntu-latest
+    services:
+      mysql:
+        image: mysql:latest
+        env:
+          MYSQL_ROOT_PASSWORD: root
+        ports:
+          - 3306
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
     steps:
       - uses: actions/checkout@v4
       - name: Restore BYOND cache
         uses: actions/cache@v4
         with:
           path: ~/BYOND
-          key: ${{ runner.os }}-byond-${{ hashFiles('dependencies.sh') }}
-      - name: Compile All Maps
-        run: |
-          bash tools/ci/install_byond.sh
-          source $HOME/BYOND/byond/bin/byondsetup
-          tools/build/build --ci dm -DCIBUILDING -DCITESTING -DALL_MAPS
-      - name: Check client Compatibility
-        uses: tgstation/byond-client-compatibility-check@v3
-        with:
-          dmb-location: tgstation.dmb
-          max-required-client-version: ${{needs.collect_data.outputs.max_required_byond_client}}
-
-  collect_data:
-    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
-    name: Collect data for other tasks
-    runs-on: ubuntu-22.04
-    outputs:
-      maps: ${{ steps.map_finder.outputs.maps }}
-      alternate_tests: ${{ steps.alternate_test_finder.outputs.alternate_tests }}
-      max_required_byond_client: ${{ steps.max_required_byond_client.outputs.max_required_byond_client }}
-    concurrency:
-      group: find_all_maps-${{ github.head_ref || github.run_id }}
-      cancel-in-progress: true
-    steps:
-      - uses: actions/checkout@v4
-      - name: Find Maps
-        id: map_finder
-        run: |
-          echo "$(ls -mw0 _maps/*.json)" > maps_output.txt
-          sed -i -e s+_maps/+\"+g -e s+.json+\"+g maps_output.txt
-          echo "Maps: $(cat maps_output.txt)"
-          echo "maps={\"paths\":[$(cat maps_output.txt)]}" >> $GITHUB_OUTPUT
-      - name: Find Alternate Tests
-        id: alternate_test_finder
-        run: |
-          ALTERNATE_TESTS_JSON=$(jq -nRc '[inputs | capture("^(?<major>[0-9]+)\\.(?<minor>[0-9]+): (?<map>.+)$")]' .github/alternate_byond_versions.txt)
-          echo "alternate_tests=$ALTERNATE_TESTS_JSON" >> $GITHUB_OUTPUT
-      - name: Collect byond client version configuration
-        id: max_required_byond_client
-        #the regex here does not filter out non-numbers because error messages about no input are less helpful then error messages about bad input (which includes the bad input)
-        run: |
-          echo "max_required_byond_client=$(grep -Ev '^[[:blank:]]{0,}#{1,}|^[[:blank:]]{0,}$' .github/max_required_byond_client.txt | tail -n1)" >> $GITHUB_OUTPUT
-
-  test_windows:
-    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
-    name: Windows Build
-    needs: [collect_data]
-    runs-on: windows-latest
-    concurrency:
-      group: test_windows-${{ github.head_ref || github.run_id }}
-      cancel-in-progress: true
-    steps:
-      - uses: actions/checkout@v4
+          key: ${{ runner.os }}-byond-${{ secrets.CACHE_PURGE_KEY }}
       - name: Restore Yarn cache
         uses: actions/cache@v4
         with:
           path: tgui/.yarn/cache
-          key: ${{ runner.os }}-yarn-${{ hashFiles('tgui/yarn.lock') }}
+          key: ${{ runner.os }}-yarn-${{ secrets.CACHE_PURGE_KEY }}-${{ hashFiles('tgui/yarn.lock') }}
           restore-keys: |
-            ${{ runner.os }}-yarn-
+            ${{ runner.os }}-build-${{ secrets.CACHE_PURGE_KEY }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
+      - name: Setup database
+        run: |
+          sudo systemctl start mysql
+          mysql -u root -proot -e 'CREATE DATABASE tg_ci;'
+          mysql -u root -proot tg_ci < SQL/tgstation_schema.sql
+          mysql -u root -proot -e 'CREATE DATABASE tg_ci_prefixed;'
+          mysql -u root -proot tg_ci_prefixed < SQL/tgstation_schema_prefixed.sql
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "^18"
+      - name: Install rust-g
+        run: |
+          bash tools/ci/install_rust_g.sh
+      - name: Install auxmos
+        run: |
+          sudo apt update || true
+          bash tools/ci/install_auxmos.sh
+      - name: Compile and run tests
+        run: |
+          bash tools/ci/install_byond.sh
+          source $HOME/BYOND/byond/bin/byondsetup
+          tools/build/build --ci -DCIBUILDING
+          bash tools/ci/run_server.sh
+      - name: Upload screenshot tests
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test_artifacts_${{ matrix.map }}
+          path: data/screenshots_new/
+          retention-days: 1
+
+  # compare_screenshots: # Disabled for now.
+  #   if: "!contains(github.event.head_commit.message, '[ci skip]') && always()"
+  #   needs: [run_all_tests]
+  #   name: Compare Screenshot Tests
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     # If we ever add more artifacts, this is going to break, but it'll be obvious.
+  #     - name: Download screenshot tests
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: artifacts
+  #     - name: ls -R
+  #       run: ls -R artifacts
+  #     - name: Setup screenshot comparison
+  #       run: npm i
+  #       working-directory: tools/screenshot-test-comparison
+  #     - name: Run screenshot comparison
+  #       run: node tools/screenshot-test-comparison/index.js artifacts code/modules/unit_tests/screenshots artifacts/screenshot_comparisons
+  #     # workflow_run does not give you the PR it ran on,
+  #     # even through the thing literally named "matching pull requests".
+  #     # However, in GraphQL, you can check if the check suite was ran
+  #     # by a specific PR, so trusting the (user controlled) action here is okay,
+  #     # as long as we check it later in show_screenshot_test_results
+  #     - name: Save PR ID
+  #       if: failure() && github.event.pull_request
+  #       run: |
+  #         echo ${{ github.event.pull_request.number }} > artifacts/screenshot_comparisons/pull_request_number.txt
+  #     - name: Upload bad screenshots
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: bad-screenshots
+  #         path: artifacts/screenshot_comparisons
+
+  test_windows:
+    if: "!contains(github.event.head_commit.message, '[ci skip]')"
+    name: Windows Build
+    runs-on: windows-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "^18"
       - name: Compile
         run: pwsh tools/ci/build.ps1
         env:
           DM_EXE: "C:\\byond\\bin\\dm.exe"
-      - name: Check client Compatibility
-        uses: tgstation/byond-client-compatibility-check@v3
+      - name: Create artifact
+        run: |
+          md deploy
+          bash tools/deploy.sh ./deploy
+      - name: Deploy artifact
+        uses: actions/upload-artifact@v4
         with:
-          dmb-location: tgstation.dmb
-          max-required-client-version: ${{needs.collect_data.outputs.max_required_byond_client}}
+          name: deploy
+          path: deploy
