BYOND 516 Compatibility (#2)
* Rename Caller Vars

* Fix World.dm Call

* Update _element.dm

* Update wanted_poster.dm

* Juke Build 0.8.1

* Fix roundstart vr config error

* Bump Dependencies, Update Node Bootstrap

* Disable SQL DBconfig

* Allow Clients to Connect Past 515

* Update __byond_version_compat.dm

* Global Proc Refs

* Juke Build Hotfix

* VSCode Upgrade

* Update Build Tools

* Update TGUI Slightly

* BYOND hrefs

* Update callbacks.dm

* Update rust_g.dm

* Fix BYOND hrefs

* Chromium Support

* Update tasks.json

* TGUI upgrade

* Statbrowser and Chat Fix

* Update skin.dmf

* Update dependencies.sh

* Revert "Update dependencies.sh"

This reverts commit 1245ae332b63c40601bd2e89a69e0e88d6a7753e.

* Fix Invalid list Accesses

* Null Safety and Runtime Fixes

* Update CI

* Update install_node.sh

* Add Missing Github Files

* Other Version of Workflows

* Update dependencies.sh

diff --git a/.github/workflows/ci_suite.yml b/.github/workflows/ci_suite.yml
--- a/.github/workflows/ci_suite.yml
+++ b/.github/workflows/ci_suite.yml
@@ -1,128 +1,139 @@
 name: CI Suite
 on:
-  workflow_dispatch:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
-
 env:
   toolchain: stable
   target: i686-unknown-linux-gnu
-
 jobs:
-  setup_tools:
-    name: Setup Tools
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Cargo Tools Cache
-        uses: actions/cache@v2
-        with:
-          path: ~/.cargo
-          key: ${{ runner.os }}-cargo
-
-      - name: Cargo Tools
-        run: |
-          cargo install ripgrep --features pcre2
-
-      - name: Rust-G Cache
-        uses: actions/cache@v2
-        with:
-          path: ~/rust-g
-          key: ${{ runner.os }}-rustg
-
-      - name: Rust-G
-        run: bash tools/ci/install_rust_g.sh
-
   run_linters:
-    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
+    if: "!contains(github.event.head_commit.message, '[ci skip]')"
     name: Run Linters
     runs-on: ubuntu-22.04
-    needs: setup_tools
     steps:
       - uses: actions/checkout@v4
-
-      - name: SpacemanDMM Cache
-        uses: actions/cache@v2
+      - name: Setup cache
+        uses: actions/cache@v4
         with:
           path: ~/SpacemanDMM
-          key: ${{ runner.os }}-spacemandmm
-
-      - name: Cargo Tools Cache
-        uses: actions/cache@v2
-        with:
-          path: ~/.cargo
-          key: ${{ runner.os }}-cargo
-
-      - name: LibGit2 Cache
-        uses: actions/cache@v2
-        with:
-          path: ~/libgit2
-          key: ${{ runner.os }}-libgit2
-
+          key: ${{ runner.os }}-spacemandmm-${{ secrets.CACHE_PURGE_KEY }}
       - name: Install Tools
-        run: |
-          bash tools/ci/install_libgit2.sh
-          sudo apt install python3 python3-{pip,venv,dev} libjpeg-dev zlib1g-dev
-          pip3 install -U pip
-          pip install setuptools
-          bash tools/ci/install_node.sh
-          bash tools/ci/install_spaceman_dmm.sh dreamchecker
-          tools/bootstrap/python -c ''
+        run: bash tools/ci/install_spaceman_dmm.sh
 
+      - uses: actions/setup-python@v6
+        with:
+          python-version: "3.13"
+          cache: "pip"
+
+      - uses: actions/setup-node@v6
+        with:
+          node-version: 20
+          cache: "yarn"
+          cache-dependency-path: ./tgui/yarn.lock
+
+      - run: pip install -r tools/requirements.txt
       - name: Run Linters
         run: |
-          bash tools/ci/check_filedirs.sh fortune13.dme
+          bash tools/ci/check_filedirs.sh hailmary.dme
           bash tools/ci/check_changelogs.sh
           find . -name "*.php" -print0 | xargs -0 -n1 php -l
           find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/json_verifier.py
           tgui/bin/tgui --lint
           tgui/bin/tgui --test
           bash tools/ci/check_grep.sh
-          tools/bootstrap/python tools/validate_dme.py < fortune13.dme
           tools/bootstrap/python -m dmi.test
           tools/bootstrap/python -m mapmerge2.dmm_test
-          ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1
-
-      - name: Annotate Lints
-        uses: yogstation13/DreamAnnotate@v2
-        if: always()
-        with:
-          outputFile: output-annotations.txt
+          ~/dreamchecker 2>&1 | bash tools/ci/annotate_dm.sh
 
   compile_all_maps:
-    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
+    if: "!contains(github.event.head_commit.message, '[ci skip]')"
     name: Compile Maps
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 14
-      - name: BYOND Cache
-        uses: actions/cache@v2
+      - name: Setup cache
+        uses: actions/cache@v4
         with:
           path: ~/BYOND
-          key: ${{ runner.os }}-byond
+          key: ${{ runner.os }}-byond-${{ secrets.CACHE_PURGE_KEY }}
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "^18"
       - name: Compile All Maps
         run: |
-          bash tools/ci/install_node.sh
           bash tools/ci/install_byond.sh
           source $HOME/BYOND/byond/bin/byondsetup
           python3 tools/ci/template_dm_generator.py
           tools/build/build dm -DCIBUILDING -DCITESTING -DALL_MAPS
 
-  run_all_tests:
-    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
-    name: Integration Tests
-    runs-on: ubuntu-22.04
-    needs: setup_tools
-    timeout-minutes: 30
+  # uncomment when they fix auxmos build
+  # auxmos:
+  #   if: "!contains(github.event.head_commit.message, '[ci skip]')"
+  #   name: Build Auxmos
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: "Putnam3145/auxmos"
+  #         ref: "6be702ec36d8024bfb93b4277004a9a755f5e92e"
+  #         path: "auxmos"
 
+  #     - name: Cache cargo registry
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cargo/registry
+  #         key: auxmos-registry-${{ hashFiles('auxmos/Cargo.lock') }}
+
+  #     - name: Cache cargo index
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cargo/git
+  #         key: auxmos-index-${{ hashFiles('auxmos/Cargo.lock') }}
+
+  #     - name: Cache cargo build
+  #       id: auxmos-cache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: auxmos/target
+  #         key: auxmos-build-target-${{ hashFiles('auxmos/Cargo.lock') }}
+
+  #     - name: Install Ubuntu Deps
+  #       if: steps.auxmos-cache.outputs.cache-hit != 'true'
+  #       run: |
+  #         sudo dpkg --add-architecture i386
+  #         sudo apt-get update
+  #         sudo apt install build-essential g++-multilib libc6-i386 libstdc++6:i386
+
+  #     - uses: actions-rs/toolchain@v1
+  #       if: steps.auxmos-cache.outputs.cache-hit != 'true'
+  #       with:
+  #         profile: minimal
+  #         toolchain: ${{env.toolchain}}
+  #         target: ${{env.target}}
+  #         override: true
+
+  #     - name: Build
+  #       if: steps.auxmos-cache.outputs.cache-hit != 'true'
+  #       run: |
+  #         cargo build --manifest-path auxmos/Cargo.toml --target=${{env.target}} --release --verbose
+  #         ldd auxmos/target/${{env.target}}/release/libauxmos.so
+
+  #     - name: Upload libauxmos artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: libauxmos
+  #         path: auxmos/target/${{env.target}}/release/libauxmos.so
+
+  run_all_tests:
+    if: "!contains(github.event.head_commit.message, '[ci skip]')"
+    name: Integration Tests
+    runs-on: ubuntu-latest
     services:
       mysql:
         image: mysql:latest
@@ -131,43 +142,22 @@ jobs:
         ports:
           - 3306
         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
-
     steps:
       - uses: actions/checkout@v4
-
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 14
-
-      - name: BYOND Cache
-        uses: actions/cache@v2
+      - name: Restore BYOND cache
+        uses: actions/cache@v4
         with:
           path: ~/BYOND
-          key: ${{ runner.os }}-byond
-
-      - name: Yarn Cache
-        uses: actions/cache@v2
+          key: ${{ runner.os }}-byond-${{ secrets.CACHE_PURGE_KEY }}
+      - name: Restore Yarn cache
+        uses: actions/cache@v4
         with:
           path: tgui/.yarn/cache
-          key: ${{ runner.os }}-yarn-${{ hashFiles('tgui/yarn.lock') }}
+          key: ${{ runner.os }}-yarn-${{ secrets.CACHE_PURGE_KEY }}-${{ hashFiles('tgui/yarn.lock') }}
           restore-keys: |
-            ${{ runner.os }}-yarn
-
-      - name: Cargo Tools Cache
-        uses: actions/cache@v2
-        with:
-          path: ~/.cargo
-          key: ${{ runner.os }}-cargo
-
-      - name: Rust-G Cache
-        uses: actions/cache@v2
-        with:
-          path: ~/rust-g
-          key: ${{ runner.os }}-rustg
-
-      - name: Rust-G
-        run: bash tools/ci/install_rust_g.sh
-
+            ${{ runner.os }}-build-${{ secrets.CACHE_PURGE_KEY }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
       - name: Setup database
         run: |
           sudo systemctl start mysql
@@ -175,24 +165,76 @@ jobs:
           mysql -u root -proot tg_ci < SQL/tgstation_schema.sql
           mysql -u root -proot -e 'CREATE DATABASE tg_ci_prefixed;'
           mysql -u root -proot tg_ci_prefixed < SQL/tgstation_schema_prefixed.sql
-
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "^18"
+      - name: Install rust-g
+        run: |
+          bash tools/ci/install_rust_g.sh
+      - name: Install auxmos
+        run: |
+          sudo apt update || true
+          bash tools/ci/install_auxmos.sh
       - name: Compile and run tests
         run: |
-          bash tools/ci/install_node.sh
           bash tools/ci/install_byond.sh
           source $HOME/BYOND/byond/bin/byondsetup
           tools/build/build --ci -DCIBUILDING
           bash tools/ci/run_server.sh
+      - name: Upload screenshot tests
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test_artifacts_${{ matrix.map }}
+          path: data/screenshots_new/
+          retention-days: 1
+
+  # compare_screenshots: # Disabled for now.
+  #   if: "!contains(github.event.head_commit.message, '[ci skip]') && always()"
+  #   needs: [run_all_tests]
+  #   name: Compare Screenshot Tests
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     # If we ever add more artifacts, this is going to break, but it'll be obvious.
+  #     - name: Download screenshot tests
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: artifacts
+  #     - name: ls -R
+  #       run: ls -R artifacts
+  #     - name: Setup screenshot comparison
+  #       run: npm i
+  #       working-directory: tools/screenshot-test-comparison
+  #     - name: Run screenshot comparison
+  #       run: node tools/screenshot-test-comparison/index.js artifacts code/modules/unit_tests/screenshots artifacts/screenshot_comparisons
+  #     # workflow_run does not give you the PR it ran on,
+  #     # even through the thing literally named "matching pull requests".
+  #     # However, in GraphQL, you can check if the check suite was ran
+  #     # by a specific PR, so trusting the (user controlled) action here is okay,
+  #     # as long as we check it later in show_screenshot_test_results
+  #     - name: Save PR ID
+  #       if: failure() && github.event.pull_request
+  #       run: |
+  #         echo ${{ github.event.pull_request.number }} > artifacts/screenshot_comparisons/pull_request_number.txt
+  #     - name: Upload bad screenshots
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: bad-screenshots
+  #         path: artifacts/screenshot_comparisons
 
   test_windows:
-    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
+    if: "!contains(github.event.head_commit.message, '[ci skip]')"
     name: Windows Build
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-node@v3
+      - name: Setup Node
+        uses: actions/setup-node@v4
         with:
-          node-version: 14
+          node-version: "^18"
       - name: Compile
         run: pwsh tools/ci/build.ps1
         env:
@@ -202,7 +244,7 @@ jobs:
           md deploy
           bash tools/deploy.sh ./deploy
       - name: Deploy artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: deploy
           path: deploy
